[[CharSetEncodings]]
deps = ["ModuleInterfaceTools", "StrAPI"]
git-tree-sha1 = "3e87f57566ee199db483028418b9847ac6120b10"
repo-rev = ""
repo-url = "https://github.com/JuliaString/CharSetEncodings.jl"
uuid = "cb9422de-a9d8-5b68-86db-ff05833ab307"
version = "0.1.1"

[[ModuleInterfaceTools]]
deps = ["Pkg", "Test"]
git-tree-sha1 = "63a2db01725cc9e186139fe7987e9bbeee7d28ab"
repo-rev = ""
repo-url = "https://github.com/JuliaString/ModuleInterfaceTools.jl"
uuid = "5cb8414e-7aab-5a03-a681-351269c074bf"
version = "0.1.1"

[[Pkg]]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Random]]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[StrAPI]]
deps = ["ModuleInterfaceTools", "Random"]
git-tree-sha1 = "adc5fdd744db2339615eb5c6fa62543de5ea529a"
repo-rev = ""
repo-url = "https://github.com/JuliaString/StrAPI.jl"
uuid = "69e7dfc3-c4d0-5e14-8d95-d6042a05b383"
version = "0.1.1"

[[Test]]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
