[[CharSetEncodings]]
deps = ["InteractiveUtils", "ModuleInterfaceTools", "Pkg", "StrAPI"]
uuid = "cb9422de-a9d8-5b68-86db-ff05833ab307"
version = "0.1.4"

[[InteractiveUtils]]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[ModuleInterfaceTools]]
deps = ["InteractiveUtils", "Pkg", "Test", "UUIDs"]
uuid = "5cb8414e-7aab-5a03-a681-351269c074bf"

[[Pkg]]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Random]]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[StrAPI]]
deps = ["InteractiveUtils", "ModuleInterfaceTools", "Pkg", "Random"]
uuid = "69e7dfc3-c4d0-5e14-8d95-d6042a05b383"
version = "0.1.3"

[[Test]]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[UUIDs]]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
