authors = ["ScottPJones <scottjones@alum.mit.edu>"]
desc = "Basic functionality for Chr type"
keywords = ["Characters"]
license = "MIT"
name = "ChrBase"
repo-rev = ""
repo-url = "https://github.com/JuliaString/ChrBase.jl"
uuid = "40048718-5f69-11e8-3be1-2f493f2f747a"
version = "0.1.0"

[deps]
CharSetEncodings = "cb9422de-a9d8-5b68-86db-ff05833ab307"
ModuleInterfaceTools = "5cb8414e-7aab-5a03-a681-351269c074bf"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StrAPI = "69e7dfc3-c4d0-5e14-8d95-d6042a05b383"
